---

- name: Configure invetory groups
  hosts: all
  become: true
  
  roles:
  - { role: ocp-terraform-pre, when: invetory_provider == "terraform" }

- hosts: bastion
  roles:
   - ssh
  tasks:
    - name: Install dependencies for ocp-ansible-wrapper project onto bastion
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - git
        - wget
        - unzip
        - ansible
        - python-passlib
        - httpd-tools
        - java-1.8.0-openjdk-headless

    - name: Clean artifact path
      file:
        state: absent
        path: "/root/openshift-ansible-wrapper"

    - name: clone ocp-ansible-wrapper project
      command: "{{ item }}"
      with_items:
       - "git clone https://github.com/mjudeikis/openshift-ansible-wrapper.git /root/openshift-ansible-wrapper"

    - name: setup stuff
      command: "make setup"
      args: 
        chdir: "/root/openshift-ansible-wrapper" 

    - name: Copy my config onto Bastion for dynamic invetory
      copy:
        src: "../{{ item }}"
        dest: "/root/openshift-ansible-wrapper/{{ item }}"
      with_items:
        - terraform/openshift-terraform-ansible/ec2/credentials.tfvars
        - terraform/openshift-terraform-ansible/ec2/config.tfvars
        - terraform/openshift-terraform-ansible/ec2/terraform.tfstate
        - group_vars/all.yml
