---

- name: Configure invetory groups
  hosts: all
  
  roles:
  - { role: ocp-terraform-pre, when: invetory_provider == "terraform" }

- include: ../openshift-ansible/playbooks/openshift-prometheus/config.yml
 