---

- name: Configure invetory groups
  hosts: all
  
  roles:
  - { role: ocp-terraform-pre, when: invetory_provider == "terraform" }

- include: ../openshift-ansible/playbooks/byo/openshift-glusterfs/config.yml
 